ruleset:
  label_full-time:
    name: "Label issue as full time"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Full Time"
    label: full time
  label_full-time_r:
    name: "Unlabel issue as full time"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Full Time")
    label: "-full time"

  label_part-time:
    name: "Label issue as part time"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Part Time"
    label: part time
  label_part-time_r:
    name: "Unlabel issue as part time"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Part Time")
    label: "-part time"

  label_contract:
    name: "Label issue as contract"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Contract"
    label: contract
  label_contract_r:
    name: "Unlabel issue as contract"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Contract")
    label: "-contract"

  label_internship:
    name: "Label issue as internship"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Internship"
    label: internship
  label_internship_r:
    name: "Unlabel issue as internship"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Internship")
    label: "-internship"

  label_remote-ok:
    name: "Label issue as remote ok"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Remote OK"
    label: remote ok
  label_remote-ok_r:
    name: "Unlabel issue as remote ok"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Remote OK")
    label: "-remote ok"

  label_fully-remote:
    name: "Label issue as fully remote"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Fully Remote"
    label: fully remote
  label_fully-remote_r:
    name: "Unlabel issue as fully remote"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Fully Remote")
    label: "-fully remote"

  label_hourly:
    name: "Label issue as hourly"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Hourly"
    label: hourly
  label_hourly_r:
    name: "Unlabel issue as hourly"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Hourly")
    label: "-hourly"

  label_salary:
    name: "Label issue as salary"
    events: [ issues ]
    when:
      - action = "opened" or action = "edited"
      - body contains "[x] Salary"
    label: salary
  label_salary_r:
    name: "Unlabel issue as salary"
    events: [ issues ]
    when:
      - action = "edited"
      - not (body contains "[x] Salary")
    label: "-salary"
